### ISSUE TITLE
Speak in Arabic Language

### ISSUE THREAD

**Issue by Sahana312** [changemyminds/GCP_TTS_ByAPIKEY#2]
Can we enter arabic text and convert it to speech?

**Comment by changemyminds** [comment]
Yes, you can enter arabic text and convert it to speech. 
The voice may be not correct because Google Cloud Text-to-Speech API don't support Arabic.
You can read the document(https://cloud.google.com/text-to-speech/docs/voices).
![image](https://user-images.githubusercontent.com/13563347/48987274-7ceb1f80-f158-11e8-819b-e2c9dcdb8f94.png)

**Comment by Sahana312** [comment]
But what do I select for language below? To make it speak arabic?

**Comment by changemyminds** [comment]
You can select any language but the voice may be not correct. You need to test.
You can test the voice on the [Google Cloud Text-to-Speech](https://cloud.google.com/text-to-speech/) web.
If the Google Cloud Text-to-Speech can't satisfy you, you can try the [Andorid Text-to-Speech](https://developer.android.com/reference/android/speech/tts/TextToSpeech). 
I hope it helps you.

**Comment by Sahana312** [comment]
Thanks @changemyminds . It did.

**Comment by changemyminds** [comment]
OK. I will close the issue. If you have any question,  you can open the issue or create new one.
